[package]
name = "nhmoon"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
crossterm = "0.27.0"
num-traits = "0.2.15"
ratatui = { version = "0.24.0", default-features = false, features = ["crossterm"] }
